# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 08:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import jobmgr.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('file', models.FileField(upload_to='%Y/%m/%d')),
                ('type', jobmgr.models.EnumField(jobmgr.models.ArtifactType, default=jobmgr.models.ArtifactType(0))),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('artifacts', models.ManyToManyField(to='jobmgr.Artifact')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('started', models.DateTimeField(default=datetime.datetime.now)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('state', jobmgr.models.EnumField(jobmgr.models.TaskState, default=jobmgr.models.TaskState(1))),
                ('message', models.CharField(blank=True, max_length=256, null=True)),
                ('artifacts', models.ManyToManyField(to='jobmgr.Artifact')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobmgr.Job')),
            ],
        ),
    ]
