# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 14:50
from __future__ import unicode_literals

from django.db import migrations
import jobmgr.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmgr', '0003_bookstyle_joboptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='source',
            field=jobmgr.models.EnumField(jobmgr.models.JobSource, default=jobmgr.models.JobSource.COLLECTION_ZIP),
            preserve_default=False,
        ),
    ]
