# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmgr', '0006_auto_20170911_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboptions',
            name='bake',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
