# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmgr', '0007_joboptions_bake'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboptions',
            name='experimental_math',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
