# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmgr', '0008_joboptions_experimental_math'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
